### ISSUE TITLE
调用相关api发送消息时，能否转义CQ码

### ISSUE THREAD

**Issue by FrostN0v0** [lgc-NB2Dev/nonebot-plugin-callapi#1]
调用相关api发送消息时，能否转义CQ码后发送
例如：
```
callapi send_msg
{"group_id": 114514,"message": "测试[CQ:face,id=63]"}
```
对应这段指令，机器人发送的消息为
`测试[CQ:face,id=63]`
能否使机器人不发生cq码，而是发送cq码对应的表情或者其它的呢？

**Comment by lgc2333** [comment]
确认为bug，将尽快修复

**Comment by lgc2333** [comment]
https://github.com/lgc-NB2Dev/nonebot-plugin-callapi/releases/tag/v0.1.1
