### ISSUE TITLE
🐛 找不到引用 `BBCodeFormatter`

### ISSUE THREAD

**Issue by KomoriDev** [lgc-NB2Dev/nonebot-plugin-callapi#2]
下面的这行代码报错
https://github.com/lgc-NB2Dev/nonebot-plugin-callapi/blob/b6e9bb9daa2d6f3ddee6c3d9dfe8e1b2a1bf38e8/nonebot_plugin_callapi/__main__.py#L21
![image](https://github.com/lgc-NB2Dev/nonebot-plugin-callapi/assets/110453675/5eef1793-13d1-451b-a416-dcd959cc194a)
应该改为
```python
from pygments.formatters.bbcode import BBCodeFormatter
```

**Comment by mute23-code** [comment]
还有 `nonebot_plugin_saa` 库是否应该require？我看商店好多使用saa的插件都在导入前用了require
